---
- name: Deploy VMs on OpenNebula
  hosts: localhost
  vars:
    ansible_python_interpreter: /home/"{{ on_name }}"/myenv/bin/python3
  become: yes
  vars_files:
    - /etc/ansible/vault.yml
  tasks:
    - name: Create a new VM
      community.general.one_vm:
        api_username: "{{ on_name }}"
        api_password: "{{ on_password }}"
        api_url: "{{ on_url }}"
        template_id: 2586
        attributes:
          name: webserver_vm
        disk_size: 6 GB
        memory: 512 MB
        vcpu: 2
        cpu: 0.1
        state: present 
      register: result
    
    - name: Output VM information
      debug:
        var: result